export const SELECT_QUESTION = "SELECT_QUESTION";
export const SELECT_PLAYERS = "SELECT_PLAYERS";
export const INITIALIZE_GAME = "INITIALIZE_GAME";
export const SET_CLOCK_TIME = "SET_CLOCK_TIME";
export const SUBMIT_ANSWERS = "SUBMIT_ANSWERS";
export const STORE_ANSWERS = "STORE_ANSWERS";